name: CI

on:
  push:
    branches:
     - main
     - master
     - next
     - 'v*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install
        run: |
          npm install
      - name: Install PeerDeps
        run: |
          npm i fastify json-schema-to-ts

      - name: Run lint
        run: |
          npm run lint
  test:
    name: Test on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install

      - name: Install PeerDeps
        run: |
          npm i fastify json-schema-to-ts

      - name: Run Transpile
        run: |
          npm run build

  types:
    name: Types
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install
        run: |
          npm install

      - name: Install PeerDeps
        run: |
          npm i fastify json-schema-to-ts

      - name: Transpile
        run: |
          npm run build

      - name: Test types
        run: |
          npm run typescript

  automerge:
    name: Automerge Dependabot PRs
    if: >
        github.event_name == 'pull_request' &&
        github.event.pull_request.user.login == 'dependabot[bot]'
    needs: 
      - lint
      - test
      - types
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: major
